#!/bin/bash
while [ 1 ]
do
CHOICE=$(
whiptail --backtitle " Программа написана на Whiptail"\
         --title "Редактирование и настройка Whiptail"\
         --menu "Клавишами верх/низ выберите справку и нажмите enter.
                 Для выхода выберите Exit." 0 0 20\
  "1)" "Следите за синтаксисoм!"\
  "2)" "Установка"\
  "3)" "Версия и документация"\
  "4)" "Первая строка и комментарий"\
  "5)" "Заглавие backtitle"\
  "6)" "Заглавие title"\
  "7)" "Сообщение infobox"\
  "8)" "Сообщение msgbox"\
  "9)" "Вывод текста textbox из файла txt"\
 "10)" "Простой yesno"\
 "11)" "Выбор статуса yesno"\
 "12)" "Кнопки yesno"\
 "13)" "Простой ввод в inputbox"\
 "14)" "Простой ввод в inputbox с exitstatus"\
 "15)" "Простой ввод в passwordbox"\
 "16)" "Индикатор прогресса"\
 "17)" "Диалог checklist"\
 "18)" "Диалог radiolist"\
 "19)" "Создание menu. Выбор option."\
 "20)" "Создание menu. function"\
 "21)" "Меню цветов whiptail"\
 "22)" "22"\
 "23)" "23"\
 "24)" "24"\
 "25)" "25"\
 "26)" "26"\
 "27)" "Псевдографика кнопок"\
 "28)" "Сайты"\
 "29)" "Редактировать мой файл whiptailEditing"\
 "30)" "Exit"\
 3>&2 2>&1 1>&3
)

result=$()
case $CHOICE in
	"1)")   
result="\n
 Следите за синтаксисoм!\n
 так писать нельза: \" 3)\"
 писать надо так: \"3)\""
        ;;
        "2)")   
result="  sudo apt-get install whiptail"
        ;;
        "3)")   
result=" Версия:
 whiptail --version\n
 Документация:
 man whiptail\n
"
        ;;
        "4)")
result=" #
 любой текс после данного знака читается как комментарий
 за исключением первой строки:
 #!/bin/bash\n
"
        ;;
        "5)")   
result=" whiptail --backtitle \"text\"\\
          --msgbox \" \" 0 0\n
 Текст заглавия в левом углу\n
"
        ;;
        "6)")   
result=" whiptail --title \"Текст в заглавии title\"\\ 
 --msgbox \" \" 0 0\n
 Всегда вставляется с чем либо"
        ;;
        "7)")
result=" TERM=vt220 whiptail --infobox \"Выводит текст infobox и возвращается в терминал.\" 26 16\n
 Последние два числа - этo высота и ширина\n
"
        ;;
        "8)")   
result=" whiptail --msgbox \"Текст сообщения msgbox\" 0 0"
        ;;
        "9)")  
result=" whiptail --textbox \"text.txt\" 0 0
 В таком виде выводит ограниченную часть текста файла\n
 whiptail --textbox \"text.txt\" 20 50 --scrolltext
 В таком виде выводит полную часть текста файла, со скролом.\n
 Для выхода активировать кнопку <ок> стрелкой вправо\n
"
        ;;
        "10)")
result=" if (whiptail --yesno \"Зделай выбор\" 0 0)  then
 echo Ys
 else
 exit/n
"
        ;;
        "11)")   
result=" if (whiptail --yesno \"Choose between Yes and No.\" 10 60) then
     echo \"You chose Yes. Exit status was \$?.\"
 else
     echo \"You chose No. Exit status was \$?.\"
 fi\n
"
        ;;
        "12)")
result=" if (whiptail --yesno \"Что вам нравится больше?\" 10 60\\
                     --yes-button \"Кола\"\\
                     --no-button \"Пепси\") then
 echo \"Вы выбрали Колу\"
 else
 echo \"Пепси\"
 fi\n
"
        ;;
        "13)")   
result=" NAME=\$(whiptail --inputbox \"Please enter your name\" 10 50 3>&1 1>&2 2>&3)
 echo \"name:\$NAME\"\n
"
        ;;
        "14)")   
result=" PET=\$(whiptail --inputbox \"Ввести в блок inputbox\" 10 60 инпутбокс 3>&1 1>&2 2>&3)
 exitstatus=$?
 if [ \$exitstatus = 0 ]; then
 echo \"В блок инпутбокс введено:\" \$PET
 else
 echo \"Ты выбрал отмену.\"
 fi\n
"
        ;;
        "15)")
result=" PASSWORD=\$(whiptail --passwordbox \"password\" 0 0 3>&1 1>&2 2>&3) 
 exitstatus=\$?
 if [ \$exitstatus = 0 ]; then
     echo \"Your password is:\" \$PASSWORD
 else
     exit"
        ;;
        "16)")
result="{
# i+=10 это шаг прогресса
     for ((i = 0 ; i <= 100 ; i+=10)); do
         sleep 1
         echo \$i
     done
# 12 60 0 это высота | длинна | не знаю
} | whiptail --gauge  \"Текст в окне\" 12 100 0\n
"
        ;;
        "17)")
result="\n
 DISTROS=\$(whiptail --checklist \\
 \"Choose preferred Linux distros\" 15 60 4 \\
 \"debian\" \"Venerable Debian\" OFF \\
 \"ubuntu\" \"Popular Ubuntu\" OFF \\
 \"fedora\" \"Stable CentOS\" ON \\
 \"centOS\" \"Rising Star Mint\" OFF 3>&1 1>&2 2>&3)
 exitstatus=\$?
 if [ \$exitstatus = 0 ];  then
      echo \"Your favorite distros are:\" \$DISTROS
 else
      echo \"You chose Cancel.\"
 fi\n
"
        ;;
        "18)")
result="\n
 CHOICE=\$(whiptail --separate-output --radiolist \"Выбор options\" 10 35 5 \\
  \"1\" \"option 1\" OFF \\
  \"2\" \"option 2\" OFF \\
  \"3\" \"option 3\" ON \\
  \"4\" \"option 4\" OFF 3>&1 1>&2 2>&3)
 if [ -z \"\$CHOICE\" ]; then
  echo \"No option was chosen (user hit Cancel)\"
 else
  echo \"The user chose \$CHOICE\"
 fi
\n
"
        ;;
        "19)")   
result="\n
 OPTION=\$(whiptail --menu \"Choose your option\" 15 60 4 \\
 \"1\" \"Option 1\" \\
 \"2\" \"Option 2\" \\
 \"3\" \"Option 3\" \\
 \"4\" \"Option 4\" 3>&1 1>&2 2>&3)
 exitstatus=\$?
 if [ \$exitstatus = 0 ]; then
      echo \"Your chosen option:\" \$OPTION
 else
      echo \"You chose Cancel.\"
 fi
\n
"
        ;;
        "20)")
result=" function advancedMenu() {
    ADVSEL=\$(whiptail  --menu \"Choose an option\" 0 0 4 \\
        \"1\" \"Option 1\" \\
        \"2\" \"Option 2\" \\
        \"3\" \"Option 3\" 3>&1 1>&2 2>&3)
    case \$ADVSEL in
        1)
            echo \"Option 1\"
            whiptail --title \"Option 1\" --msgbox \"You chose option 1. Exit status \$?\" 8 45
        ;;
        2)
            echo \"Option 2\"
            whiptail --title \"Option 1\" --msgbox \"You chose option 2. Exit status \$?\" 8 45
        ;;
        3)
            echo \"Option 3\"
            whiptail --title \"Option 1\" --msgbox \"You chose option 3. Exit status \$?\" 8 45
        ;;
    esac
}
advancedMenu
\n"
        ;;
        "21)")   
./whiptailMenuColor
        ;;
        "22)")   
result=" 22
\n"
        ;;
        "23)")   
result=" 23
\n"
        ;;
        "24)")   
result=" 24
\n"
        ;;
        "25)")   
result=" 25
\n"
        ;;
        "26)")
result=" 26
\n"
        ;;
        "27)")   
result=" --fb \\
\n"
        ;;
        "28)")   
result="\n
https://linux.die.net/man/1/whiptail
https://en.wikibooks.org/wiki/Bash_Shell_Scripting/Whiptail
http://rus-linux.net/MyLDP/consol/whiptail.html
"
        ;;
        "29)")
ne whiptailEditing
        ;;
        "30)")   
exit
        ;;
esac
whiptail --msgbox "$result" 0 0
done
exit